image:
    - Visual Studio 2017

build: off

init:
  - git config --global core.autocrlf input

install:
  - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - SET PATH=%JAVA_HOME%\bin;%PATH%

  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://github.com/sbt/sbt/releases/download/v1.3.2/sbt-1.3.2.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - SET PATH=C:\sbt\sbt\bin;%PATH%

test_script:
  - sbt "test; scripted"

cache:
  - '%LOCALAPPDATA%\Coursier\Cache\v1'
  - '%USERPROFILE%\.ivy2\cache'
  - '%USERPROFILE%\.sbt'
